# This file contains default values, and does not need to be edited. All
# important settings can be changed from the admin interface.

defaults: &defaults
  site_title: Whippy Edition
  site_short_description: ''
  site_description: ''
  site_extended_description: ''
  site_terms: ''
  site_contact_username: 'notice'
  site_contact_email: 'whippyshou@gmail.com'
  registrations_mode: 'open'
  profile_directory: true
  closed_registrations_message: ''
  timeline_preview: false
  show_staff_badge: true
  preview_sensitive_media: false
  noindex: true
  theme: 'default'
  trends: false
  trends_as_landing_page: false
  trendable_by_default: false
  reserved_usernames:
    - admin
    - support
    - help
    - root
    - webmaster
    - administrator
    - mod
    - moderator
  disallowed_hashtags: # space separated string or list of hashtags without the hash
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  show_domain_blocks: 'disabled'
  show_domain_blocks_rationale: 'disabled'
  require_invite_text: false
  backups_retention_period: 7
  captcha_enabled: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
